language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - develop
    - master

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

git:
  submodules: false

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ac559b8d8fd5527c8e95
    on_success: change
    on_failure: always
    on_start: never
